### ISSUE TITLE
absolute off-power instead of deepsleep

### ISSUE THREAD

**Issue by mzy2240** [tstoegi/MicroWakeupper#1]
Hi, this is an amazing and useful board for battery-powered esp project.  If I understand correctly, the microwakeupper board will wake up the deepsleeping esp. Is it possible to power up the esp when needed instead of keeping it in the deep sleep mode? Will that make the battery last longer? Thanks.

**Comment by tstoegi** [comment]
Thanks for your feedback. 
Just cut the jumper labeled as "J1" and the shield will take care about turning VIN on/off (in the case of the external event).
