### ISSUE TITLE
Gerber

### ISSUE THREAD

**Issue by danielducu** [tstoegi/MicroWakeupper#4]
Any chances to get the Gerber file ? Thanks

**Comment by tstoegi** [comment]
Added to the pcb folder. Enjoy!

**Comment by danielducu** [comment]
> Added to the pcb folder. Enjoy!

Thanks a lot man! Would definitely buy some directly from you just to support your great work. Greetings from Spain.

**Comment by tstoegi** [comment]
U are welcome.
